export const cloudyConditions = [
  "Partly cloudy",
  "Cloudy",
  "Overcast",
  "Mist",
  "Blowing snow",
  "Fog",
  "Freezing fog",
];

export const rainyConditions = [
  "Patchy rain possible",
  "Patchy sleet possible",
  "Thundery outbreaks possible",
  "Patchy light drizzle",
  "Light drizzle",
  "Heavy freezing drizzle",
  "Patchy light rain",
  "Light rain",
  "Moderate rain at times",
  "Moderate rain",
  "Heavy rain at times",
  "Heavy rain",
  "Moderate or heavy freezing rain",
  "Light sleet",
  "Moderate or heavy sleet",
  "Light rain shower",
  "Moderate or heavy rain shower",
  "Torrential rain shower",
  "Light sleet showers",
  "Moderate or heavy sleet showers",
  "Patchy light rain with thunder",
  "Moderate or heavy rain with thunder",
  "Patchy light snow with thunder",
];

export const snownyConditions = [
  "Patchy freezing drizzle possible",
  "Blowing snow",
  "Blizzard",
  "Freezing fog",
  "Freezing drizzle",
  "Heavy freezing drizzle",
  "Light freezing rain",
  "Moderate or heavy freezing rain",
  "Patchy light snow",
  "Light snow",
  "Patchy moderate snow",
  "Moderate snow",
  "Patchy heavy snow",
  "Heavy snow",
  "Ice pellets",
  "Light showers of ice pellets",
  "Moderate or heavy showers of ice pellets",
  "Patchy light snow with thunder",
  "Moderate or heavy snow with thunder",
];

export default cloudyConditions;